# encoding: utf-8
## YAML Template.
---
categories:
  -
    - 餐饮美食
    -
      - 火锅
      - 干锅
      - 自助
      - 寿司
      - 烧烤
      - 料理
      - 西餐
      - 海鲜
      - 甜点
      - 美食
      - 其他
  -
    - 休闲娱乐
    -
      - 摄影
      - 高尔夫
      - 保龄球
      - 温泉
      - KTV
      - 电影戏剧
      - 户外
      - 台球桌游
      - 游乐场
      - 酒吧
      - 其他
  -
    - 美容保健
    -
      - 护肤
      - 大品牌
      - 彩妆
      - 美容美体
      - 美发
      - SPA
      - 按摩足疗
      - 养生健身
      - 香水
      - 口腔护理
      - 其他
  -
    - 网上购物
    -
      - 虚拟
      - 数码家电
      - 食品
      - 母婴
      - 美容配饰
      - 家居
      - 户外文体
      - 服饰
      - 其他
  -
    - 旅游酒店
    -
      - 旅游
      - 酒店
      - 其他
  -
    - 优惠券票
    -
      - 演唱会
      - 其他
  -
    - 其他
    -
      - 课程
      - 眼镜
      - 汽车保养
      - 其他
        
        